### PR TITLE
Escape query parameter in searches

### LINKED ISSUE #707: Search term including / crashes
https://sentry.io/share/issue/b184417724f44a2d8d8427bdf8a088ab/

### PR DESCRIPTION
**Pull request by eduardoj**
Prevent crashing in search terms including `/`.

Fixes #707.

### CODE REVIEW

File: app/controllers/search_controller.rb [hunk 1]
```diff
@@ -2,17 +2,18 @@ class SearchController < ApplicationController
   skip_before_action :authenticate_user!, only: [:result]
   def result
     # First search in morphology mode, if fails — retry in wildcard mode
+    param_q = ThinkingSphinx::Query.escape(params[:q])
```
Comment (hennevogel) [inline app/controllers/search_controller.rb:5]:
```suggestion
    search_query = ThinkingSphinx::Query.escape(params[:q])
```

**Review by hennevogel — CHANGES_REQUESTED** [review]

File: app/controllers/search_controller.rb (hunk 1 above)
Comment (eduardoj) [reply app/controllers/search_controller.rb]: Changed. Please check it out again.

**Review by hennevogel — APPROVED** [review]
