### PR TITLE
Fix authenticity_token bug

### LINKED ISSUE #191: Can't verify CSRF token authenticity for creating project
User is directed to error page upon saving project.

### PR DESCRIPTION
**Pull request by AnkushMalik**
Closes #191

### CODE REVIEW

File: spec/features/project_management_spec.rb [hunk 1]
```diff
@@ -86,6 +86,7 @@
     visit '/projects/new'
     fill_in 'project_description', with: '_italic_ **bold**'
     click_link 'Preview'
+    wait_for_preview
```
Comment (hennevogel) [inline spec/features/project_management_spec.rb]: Hm... `have_css` already waits the `Capybara.default_wait_time` so would `page.find('#preview-contents')`. Why do we need this method? What are you trying to achieve?

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -5,6 +5,7 @@ class ApplicationController < ActionController::Base
   before_filter :authenticate_user!
   before_filter :load_news
   before_filter :set_episode
+  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
```
Comment (hennevogel) [inline app/controllers/application_controller.rb]: I fail to understand how this would *fix* the problem. It would just [skip protection](http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html) for `POST`ing json, which we don't do, or do I miss something?

**Comment by hennevogel** [comment]
hey @AnkushMalik thank you for your contributions 💐😍

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (AnkushMalik) [reply app/controllers/application_controller.rb]: The token provided by the rails in the beginning and the time we click submit are different because when ajax calls the markdown controller new auth token is provided so I skipped protection only if request format is of application/json.

File: spec/features/project_management_spec.rb (hunk 1 above)
Comment (AnkushMalik) [reply spec/features/project_management_spec.rb]: here capybara doesn't wait for our ajax request of previewing markdown to complete so it doesn't find that div.
So from this [link](https://robots.thoughtbot.com/automatically-wait-for-ajax-with-capybara), I tried to add this function but the error still persists.

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (hennevogel) [reply app/controllers/application_controller.rb]: > The token provided by the rails in the beginning and the time we click submit are different because when ajax calls the markdown controller new auth token is provided

Sure thing, I understand the problem :-) 

> so I skipped protection only if request format is of application/json.

What I don't understand is the solution.

1. We **GET** `/markdown/preview?source='## blah'` as **json**. ` protect_from_forgery` isn't used for **GET**, hence your change doesn't apply.
2. Then we **POST** the same data to `/projects` as **html**.  Your `protect_from_forgery` `before_filter` isn't used, as it's not **json**, hence your change doesn't apply.

How does that **fix** the problem?

File: spec/features/project_management_spec.rb (hunk 1 above)
Comment (hennevogel) [reply spec/features/project_management_spec.rb]: Did you follow the [first link](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends) from your blog post? This is what the capybara README has to say:

```
When working with asynchronous JavaScript, you might come across situations
where you are attempting to interact with an element which is not yet present
on the page. Capybara automatically deals with this by waiting for elements to
appear on the page.
```

The rest of the thoughtbot blog post is about fixing race conditions between two requests happening at the same time (`click_link` & `reload_page`), this is not what is happening here.

So effectively you just have increased the time capbybara waits for the `bold` and `italic` elements to appear from 2 seconds (default) to 7 seconds. Which can also do by setting `Capybara.default_wait_time = 7` instead of adding all this code.

So why where you doing this? Did you run into a timeout locally?

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (AnkushMalik) [reply app/controllers/application_controller.rb]: my apologies for the late reply, I used
> protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

after checking these links : [1](https://coderwall.com/p/8z7z3a/rails-4-solution-for-can-t-verify-csrf-token-authenticity-json-requests) & [2](https://stackoverflow.com/a/10049965/5129516) ,since i dont want to close csrf check.
___
> protect_from_forgery isn't used for GET, hence your change doesn't apply.

^ I didnt get any strong proof but I think maybe in line:8 protect_from_forgery is triggered only when request.format is application/json 🤔

File: spec/features/project_management_spec.rb (hunk 1 above)
Comment (AnkushMalik) [reply spec/features/project_management_spec.rb]: Yes, I was having timeout error, that's why I tried to wait for ajax and also i dont want to increase capybara timeout error just for one feature testing.

( tbh, I don't have much experience with capybara, so was just trying to fiddle around 😅)

File: app/controllers/application_controller.rb (hunk 2 above)
Comment (hennevogel) [reply app/controllers/application_controller.rb]: Skipping forgery protection in general is not something we want to do right. But as I said, the only type of requests where forgery protection is running are POST requests. I really don't think you can disable the token update for the session like this by skipping this.

Can you try something? When rendering the preview also change the token of the input field? 

```html
<input name="authenticity_token" value="$TOKEN" type="hidden">
```

There is a view helper called `form_authenticity_token` that gives you the current token.

File: spec/features/project_management_spec.rb (hunk 1 above)
Comment (hennevogel) [reply spec/features/project_management_spec.rb]: That's a lot of code for changing something that probably depends on the hardware the test runs on. I would rather read `Capybara.default_wait_time` from an environment variable so you can set this individually and we can leave the default as it is. Please do it this way :-)

Comment (AnkushMalik) [reply spec/features/project_management_spec.rb]: actually, I think instead of changing capybara's default wait time we should use wait as :

    expect(page).to have_selector(:css, "em", text: 'italic', wait: 7)

because capybara will wait for every test whether some element does exist or not.
(please do tell me if I m wrong somewhere 😅 )

However, I think there's some other problem since none of these works, even after waiting or  setting the time to 30 seconds! , that's why I tried all those lines of code but even those seem to pass only sometimes ...😕

Comment (hennevogel) [reply spec/features/project_management_spec.rb]: Try just increasing the `Capybara.default_wait_time` in the helper, see if that helps.

Comment (AnkushMalik) [reply spec/features/project_management_spec.rb]: already did that, no success.

**Comment by AnkushMalik** [comment]
failing test cases were resolved in [this](https://github.com/SUSE/hackweek/pull/202).

**Comment by hennevogel** [comment]
Hey @AnkushMalik sorry that I was not responsive for so long. Too much stuff happening in `openSUSE/open-build-service` 😬 This is exactly what I meant! Thanks.
