### PR TITLE
Fix no fallback route when enrolling on announcements

### LINKED ISSUE #1666: NoMethodError: undefined method `back_url' for #<AnnouncementsController:0x000000006e09d8>
Sentry Issue: [HACKWEEK-81](https://opensuse.sentry.io/issues/6011416900/?referrer=github_integration)

```
NoMethodError: undefined method `back_url' for #<AnnouncementsController:0x000000006e09d8>

            target.public_send get_method_for_string str
                  ^^^^^^^^^^^^
  app/controllers/announcements_controller.rb:56:in `block (2 levels) in enroll'
    format.html { redirect_to :back }
  app/controllers/announcements_controller.rb:55:in `enroll'
    respond_to do |format|
...
(91 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by danidoni**
Fixes #1666

### CODE REVIEW

File: app/controllers/announcements_controller.rb [hunk 1]
```diff
@@ -53,7 +53,7 @@ def enroll
     announcement.enroll! current_user
 
     respond_to do |format|
-      format.html { redirect_to :back }
+      format.html { redirect_back(fallback_location: root_path) }
```
Comment (hennevogel) [inline app/controllers/announcements_controller.rb:56]:
```suggestion
      format.html { redirect_back_or_to root_path }
```

**Review by hennevogel — CHANGES_REQUESTED** [review]

**Review by hennevogel — APPROVED** [review]
